### ISSUE TITLE
Add issue template: bug report

### ISSUE THREAD

**Issue by adityabisoi** [the-browser-toolbox/save-notes#3]
Add an issue template for reporting bugs in the project.

**Comment by ak7550** [comment]
Hello @adityabisoi , I am Aniket. I am a KWOC participant. Would you like to assign this to me ?

**Comment by ak7550** [comment]
I want to work on this issue.

**Comment by adityabisoi** [comment]
@ak7550 Go ahead.

**Comment by ak7550** [comment]
@adityabisoi  I have sent PR on this issue.  Check it at  [Created a bug report issue template #14](https://github.com/the-browser-toolbox/save-notes/pull/14). Let me know if any changes are required.
