### ISSUE TITLE
Add manifest file

### ISSUE THREAD

**Issue by adityabisoi** [the-browser-toolbox/save-notes#4]
Add manifest file to the extension.

See the wiki page for resources: https://github.com/the-browser-toolbox/docs/wiki

**Comment by codewithvk** [comment]
Can you assign me? I am happy to work on this issue.

**Comment by adityabisoi** [comment]
@codewithvk Go ahead.

**Comment by codewithvk** [comment]
@adityabisoi  Someone already added manifest on pull request. So can you please check and confirm with me?

**Comment by adityabisoi** [comment]
@codewithvk Go ahead, I will take care of that.
