### ISSUE TITLE
Add gulpfile

### ISSUE THREAD

**Issue by adityabisoi** [the-browser-toolbox/save-notes#5]
`gulp.js` is a workflow automation tool for JavaScript. Write a `gulpfile` for the project with the following operations: `watch`,  `build`, and `default` for running both simultaneously.

**Comment by RahulSharma4329** [comment]
Hey i would like to work on this issue can you assign this to me.

**Comment by RahulSharma4329** [comment]
@adityabisoi The pull request for this issue had been created by me and has been merged, kindly close this issue.
The pull request was #22
