### ISSUE TITLE
Add popup page and background script

### ISSUE THREAD

**Issue by adityabisoi** [the-browser-toolbox/save-notes#6]
Add a simple popup page showing `Hello World` and a background script to the extension. These will be the initial setup files, the popup page is for UI, and the background script is for handling the business logic of the extension.

**Resources:** https://github.com/the-browser-toolbox/docs/actions/new

**Comment by Palash1999** [comment]
I worked on this and opened the pull request.

**Comment by adityabisoi** [comment]
@Palash1999 Please make a PR only after you are assigned.

**Comment by Palash1999** [comment]
Sorry, I didn't know that I am new to this, do I need to make a PR again?

**Comment by adityabisoi** [comment]
@Palash1999 No
