### ISSUE TITLE
Add linting and formatting

### ISSUE THREAD

**Issue by adityabisoi** [the-browser-toolbox/save-notes#8]
For consistency in styling, linters, and code formatters are used. The most popular ones for JavaScript are `ESLint` and `Prettier`.
Add linting and formatting support to the project.

**Tip:** Use the configuration files and scripts at https://gitlab.com/adityabisoi/aossie-scholar

**Comment by aashu** [comment]
hey @adityabisoi , i would like to work on this issue. can you please assign it to me?

 if i understand correctly i have to put config files and add relavant package in package.json taking reference from gitlab repo ?

**Comment by adityabisoi** [comment]
@aashu Yes. Go ahead.
